services:
  # Inventario Service - Port 8081
  inventario:
    build: ./inventario
    container_name: cloud2-api-inventario
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST:-20.81.232.159}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-duoc}
      DB_USER: ${DB_USER:-duoc}
      DB_PASS: ${DB_PASS:-84oL4mK6cM8w7SK}
    restart: always
    networks:
      - vet-network

  # Historial Service - Port 8082
  historial:
    build: ./historial
    container_name: cloud2-api-historial
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST:-20.81.232.159}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-duoc}
      DB_USER: ${DB_USER:-duoc}
      DB_PASS: ${DB_PASS:-84oL4mK6cM8w7SK}
    restart: always
    networks:
      - vet-network

  # Agenda Service - Port 8083
  agenda:
    build: ./agenda
    container_name: cloud2-api-agenda
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${DB_HOST:-20.81.232.159}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-duoc}
      DB_USER: ${DB_USER:-duoc}
      DB_PASS: ${DB_PASS:-84oL4mK6cM8w7SK}
    restart: always
    networks:
      - vet-network

  # Empleados Service - Port 8084
  empleados:
    build: ./empleados
    container_name: cloud2-api-empleado
    ports:
      - "8084:8084"
    environment:
      DB_HOST: ${DB_HOST:-20.81.232.159}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-duoc}
      DB_USER: ${DB_USER:-duoc}
      DB_PASS: ${DB_PASS:-84oL4mK6cM8w7SK}
    restart: always
    networks:
      - vet-network

networks:
  vet-network:
    driver: bridge
